ALTER TABLE categories
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN modified_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE products
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN modified_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

UPDATE categories
SET created_at = CURRENT_TIMESTAMP - INTERVAL '1 day' * (id % 10),
    modified_at = CURRENT_TIMESTAMP - INTERVAL '1 hour' * (id % 24);

UPDATE products
SET created_at = CURRENT_TIMESTAMP - INTERVAL '1 day' * (id % 15),
    modified_at = CURRENT_TIMESTAMP - INTERVAL '2 hour' * (id % 12);